version: "3.8"

services:
  wiremock:
    image: wiremock/wiremock:latest
    container_name: wiremock
    ports:
      - "8080:8080"
    volumes:
      - ./stubs:/home/wiremock

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
      - ./database/data:/var/lib/postgresql/data
    networks:
      - app.network

networks:
  app.network:
    driver: bridge

volumes:
  postgres.data: