server:
  port: 8089
  servlet:
    context-path: /querycep/api

logging:
  level:
    com.empresa: ${LOG_LEVEL:DEBUG}

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=querycep}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: SpringBootJPAHikariCP
      minimumIdle: 20
      maximumPoolSize: 200
      connectionTimeout: 30000
      idleTimeout: 30000
      maxLifetime: 2000000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          default_schema: querycep

cloud:
  aws:
    region:
      static: us-east-1
    credentials:
      access-key: test
      secret-key: test
    stack-name: localstack
    sqs:
      listener:
        enabled: true
        max-messages: 10
        visibility-timeout: 30
        wait-time-seconds: 20
